// User roles
export enum UserRoles {
  CARGADOR = "CARGADOR",
  VISUALIZADOR = "VISUALIZADOR",
  GERENTE = "GERENTE",
  DIRECTOR = "DIRECTOR",
  VP = "VP",
  GTEGRAL = "GTEGRAL",
  ADMINISTRADOR = "ADMINISTRADOR",
  PAGADOR = "PAGADOR",
  SUPERUSER = "SUPERUSER"
}
