name: I2p CI in QA

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy I2P over Claxson Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.QA_SSH_HOST}}
          username: ${{ secrets.QA_SSH_USERNAME }}
          password: ${{ secrets.QA_SSH_PASSWORD }}
          script: |
            cd /opt/webapps/i2p
            pm2 stop i2p   # stop app
            git pull
            npm run build
            cd dist
            pm2 start i2p   # start app.