name: Prueba 1

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - run: cd /opt/webapps/i2p
    - run: pm2 stop i2p
    - run: git pull
    - run: npm run build
    - run: pm2 start i2p
