name: Prueba 1

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - run: pwd
    - run: ping localhost -c 5
    - run: ping admapps01 -c 5
    - run: cd /opt/webapps/i2p
    - run: pwd      
